<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ELIMINAR</title>
</head>
<body>
<h1>ELIMINAR</h1>
    <form class="" action= "eliminar_eq.PHP" method="post">
        <label for="">ID_EQUIPO</label>
        <input type="text" name="ID_EQUIPO"values="">

        <label for="">EQ_NOMBRE</label>
        <input type="text" name="EQ_NOMBRE"values="">

        <label for="">EQ_APODO</label>
        <input type="text" name="EQ_APODO"values="">

        <label for="">EQ_DIRECCION</label>
        <input type="text" name="EQ_DIRECCION"values="">

        <label for="">EQ_FECHA_FUNDACION</label>
        <input type="text" name="EQ_FECHA_FUNDACION"values="">

        <label for="">ID_ESTADIO</label>
        <input type="text" name="ID_ESTADIO"values="">

        <input type="submit" name=""values="Guardar">

</form>
    </body>
</html>